### ISSUE TITLE
Two problem about cuStreamComp

### ISSUE THREAD

**Issue by ZhangJingrong** [knotman90/cuStreamComp#1]
Hi～
 That is a great job.  During the test,  I find two problems.  I list them here for discussion.
- File  " cuCompactor.cuh": The function "pow2i" missed the return statement at end of non-void function.

``` C++
  __device__ __inline__ int pow2i (int e){   

* return* 1<<e;  

 }  
```
-  File  " cuCompactor.cuh": In the step of calculating warp offset, the loop number for bit manipilation shoud be 6 instand of 5 because 32=(100000)B.

``` C++
 if(w_i==0 && w_l<blockDim.x/warpSize){  
            int w_i_u=0;  

            for(int j=0;j<*6*;j++){  

            int b_j =__ballot( warpTotals[w_l] & pow2i(j) );  

            w_i_u += ((__popc(b_j & t_m)  ) << j);  

            }//end for(int j=0;j<6;j++)  

            warpTofor(int j=0;j<32;j++)tals[w_l]=w_i_u;  

            __syncthreads();  
}// end if (w_i==0 && w_l<blockDim.x/warpSize)  

```

**Comment by knotman90** [comment]
Hi, I've fixed the pow2i issue.

Regarding the other issue I?m quite sure your're right.  It should do 5 iteration since `5 = log_2(32)` hence `6` is the right upper bound for the loop.

Unfortunately I'm not able to test the effect of this modification because I will not be able to run on any cuda device untile the next week? Could you do it?

In the next days I'll also push a couple of test suite and benchmarks.

Thank you!

**Comment by ZhangJingrong** [comment]
Hi~
I think I can run the tests. After you push the test suite and benchmarks, I will test them and upload the results. 
Here I list the information of my machine here, just in case.

> CPU: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
> GPU: Tesla K20c (4799MB)
> CUDA: Cuda compilation tools, release 7.0, V7.0.27

**Comment by knotman90** [comment]
I've added a test on integer only for various input size and various blocksize.

Things that have to be done:
1. testing the modification proposed by @ZhangJingrong 
2. test on a better card than mine (gtx 970M) with possible larger data size
3. compare performance with outher libraries (thrust mainly)
4: add test for other datatypes and random values.

**Comment by ZhangJingrong** [comment]
I am so sorry for respond you until now. Here I list the results here ( on card Tesla K20c)

> (128,32,0)
> (128,64,0)
> (128,128,0)
> (128,256,0)
> (128,512,0)
> (128,1024,0)
> (256,32,0)
> (256,64,0)
> (256,128,0)
> (256,256,0)
> (256,512,0)
> (256,1024,0)
> (512,32,0)
> (512,64,0)
> (512,128,10)
> (512,256,0)
> (512,512,0)
> (512,1024,0)
> (1024,32,0)
> (1024,64,0)
> (1024,128,0)
> (1024,256,10)
> (1024,512,0)
> (1024,1024,0)
> (2048,32,0)
> (2048,64,0)
> (2048,128,0)
> (2048,256,10)
> (2048,512,0)
> (2048,1024,0)
> (4096,32,0)
> (4096,64,0)
> (4096,128,0)
> (4096,256,0)
> (4096,512,0)
> (4096,1024,0)
> (8192,32,0)
> (8192,64,10)
> (8192,128,0)
> (8192,256,0)
> (8192,512,0)
> (8192,1024,0)
> (16384,32,0)
> (16384,64,0)
> (16384,128,0)
> (16384,256,10)
> (16384,512,0)
> (16384,1024,0)
> (32768,32,0)
> (32768,64,0)
> (32768,128,0)
> (32768,256,0)
> (32768,512,0)
> (32768,1024,0)
> (65536,32,0)
> (65536,64,10)
> (65536,128,0)
> (65536,256,0)
> (65536,512,0)
> (65536,1024,0)
> (131072,32,0)
> (131072,64,0)
> (131072,128,0)
> (131072,256,0)
> (131072,512,0)
> (131072,1024,0)
> (262144,32,10)
> (262144,64,0)
> (262144,128,0)
> (262144,256,0)
> (262144,512,0)
> (262144,1024,0)
> (524288,32,10)
> (524288,64,0)
> (524288,128,0)
> (524288,256,0)
> (524288,512,0)
> (524288,1024,0)
> (1048576,32,0)
> (1048576,64,20)
> (1048576,128,0)
> (1048576,256,0)
> (1048576,512,0)
> (1048576,1024,10)
> (2097152,32,0)
> (2097152,64,10)
> (2097152,128,10)
> (2097152,256,0)
> (2097152,512,0)
> (2097152,1024,0)
> (4194304,32,10)
> (4194304,64,10)
> (4194304,128,0)
> (4194304,256,20)
> (4194304,512,10)
> (4194304,1024,20)
> (8388608,32,30)
> (8388608,64,0)
> (8388608,128,10)
> (8388608,256,0)
> (8388608,512,10)
> (8388608,1024,20)
> (16777216,32,50)
> (16777216,64,20)
> (16777216,128,20)
> (16777216,256,20)
> (16777216,512,10)
> (16777216,1024,10)
> (33554432,32,100)
> (33554432,64,50)
> (33554432,128,20)
> (33554432,256,30)
> (33554432,512,20)
> (33554432,1024,20)
> (67108864,32,190)
> (67108864,64,90)
> (67108864,128,60)
> (67108864,256,50)
> (67108864,512,50)
> (67108864,1024,60)
> (134217728,32,350)
> (134217728,64,190)
> (134217728,128,100)
> (134217728,256,80)
> (134217728,512,80)
> (134217728,1024,90)
> (268435456,32,700)
> (268435456,64,360)
> (268435456,128,200)
> (268435456,256,170)
> (268435456,512,180)
> (268435456,1024,180)
> (536870912,32,1400)
> (536870912,64,710)
> (536870912,128,390)
> (536870912,256,350)
> (536870912,512,340)
> (536870912,1024,370)
> ALL TEST PASSED

**Comment by ZhangJingrong** [comment]
About the second problem, when the predicate function do not eliminate any data, the result  will go wrong. 
I change the function "initData" to make **h_data[i]=1 for all i**,  so that the size of output equals the size of input.

``` C++
void initiData(int *h_data, uint NELEMENTS,uint &goodElements,bool randomOrStride){

    ushort stride = 4;
    for (int i = 0; i < NELEMENTS; ++i) {
        if(randomOrStride)
            h_data[i] = i%stride;
        else
            //h_data[i] =(rand()%100 <= randBound) ? 1 : 0;
            h_data[i] =1;
        if(h_data[i])
            goodElements++;
        printf("[%d]=%d ", i, h_data[i]);
    }
    printf("\n");
}

```

The test program shows error:

> cuCompact: ../src/tests.cu:47: void checkVector(int*, uint, uint): Assertion `predicate(h_data[i])' failed.

As you have said the 6 is the right upper bound for the loop. So the loop should be like this:

``` C++
for(int j=0;j<=5;j++)
```

After I changed the loop number, the test passed.

**Comment by knotman90** [comment]
Great!
So create a pull request with the modification and I'll merge it.

Thanks.

I'll mark this closed as soon as I receive the pull Request.

**Comment by ZhangJingrong** [comment]
Hi~ 
The pull request has been received, so it's time to close this issue. If you need any help, like the GPU environment,etc.  just let me know :)
